apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-cicd
  source:
    repoURL: git@github.com:raphaelmulenda/kubernetes-cicd-project.git
    targetRevision: HEAD
    path: kubernetes/apps/2048-game/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: game-2048-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true