argocd-apps:
  projects:
    argo-cicd:
      namespace: argocd
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false

  # rootApplication:
  #   enabled: true
  #   name: argocd-appset-apps
  #   namespace: argocd
  #   project: argo-cicd
  #   source:
  #     repoURL: git@github.com:raphaelmulenda/kubernetes-cicd-project.git
  #     targetRevision: HEAD
  #     path: kubernetes/argocd-root-app
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: argocd
  #   syncPolicy:
  #     syncOptions:
  #       - CreateNamespace=true
  #     automated:
  #       prune: true
  #       selfHeal: true

  applications:
    argocd-appset-apps:
      namespace: argocd
      project: argo-cicd
      source:
        repoURL: git@github.com:raphaelmulenda/kubernetes-cicd-project.git
        targetRevision: HEAD
        path: kubernetes/argocd-root-app/
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true

# argocd-apps:
#   rootApplication:
#     enabled: true
#     name: argocd-appset-apps
#     namespace: argocd
#     project: argo-cicd
#     source:
#       repoURL: git@github.com:raphaelmulenda/kubernetes-cicd-project.git
#       targetRevision: HEAD
#       path: kubernetes/appsets
#     destination:
#       server: https://kubernetes.default.svc
#       namespace: argocd
#     syncPolicy:
#       syncOptions:
#         - CreateNamespace=true
#       automated:
#         prune: true
#         selfHeal: true
