argocd-apps:
  projects:
    klabater:
      namespace: argocd
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false


  applications:
    argoproj:
      namespace: argocd
      project: argo-cicd
      source:
        repoURL: git@github.com:raphaelmulenda/kubernetes-cicd-project.git
        targetRevision: HEAD
        path: kubernetes/argoproj/
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
